In [1]:
doc = []
doc_index = []
for i in range(1402):
    try:
        with open('data\\Train\\dataTrainComplete\\' + str(i) + '.txt', 'r', encoding='UTF-8') as f:
            doc.append(''.join(list(f)))
            doc_index.append(i)
    except:
        pass
    
print(doc[:2])
print(doc_index[:2])

['梅雨季來臨，文旦黑點病易發生，請注意病徵，以及早加強防治措施。\n5月已進入梅雨季節，近日連續降雨，為文旦黑點病開始感染的時機，往年文旦在經過4-6月的春雨及梅雨季後，原來長得亮麗的果實外表，會開始出現許多小黑點，現在文旦已開始進入中果期，花蓮區農業改良場呼籲應注意防治。\n除冬季清園作業外，在4-8月時應每月施用一次56%貝芬硫\x7f可濕性粉劑800倍、或22.7%\x7f硫\x7f水懸劑1000倍、或80%鋅錳乃浦可濕性粉劑500倍、或33%鋅錳乃浦水懸劑500倍等政府核准登記使用之藥劑防治，並依登記使用方法使用，尤其雨前及雨後要特別加強防治，若遇連續降雨時則可利用間歇時分區進行施藥以即時達到防治效果。\n', '夏季為斜紋夜盜及甜菜夜蛾發生盛期，請加強注意，及時防治避免損失。\n夏日乾燥炎熱的氣候，正是許多農作物害蟲好發的時機，花蓮區農業改良場籲請農民注意斜紋夜盜及甜菜夜蛾的防治，以免造成作物損失。隨著氣溫增高，許多農作物害蟲也隨之變得活躍，由監測數據顯示宜蘭地區開始出現夜蛾類害蟲的高峰，其中包括斜紋夜蛾和甜菜夜蛾。斜紋夜蛾一般人稱「黑肚蟲」，其食性幾乎是見綠就吃，是種植蔬菜的農友最傷腦筋的害蟲之一。另外青蔥產區除了斜紋夜蛾之外，還有甜菜夜蛾危害，孵化的幼蟲藏匿於蔥管內啃食青蔥，而炎熱的天氣更加速這兩種害蟲繁衍，為了減輕其所造成的嚴重經濟損失，行政院農業委員會花蓮區農業改良場呼籲花蓮宜蘭地區的農友持續進行防治工作，切勿輕忽大意。\n1.大量誘殺雄蟲：懸掛性費洛蒙誘蟲盒於園區外圍，藉由大量誘殺雄蟲，降低雌蟲的交尾機率，可使族群密度受到壓抑。懸掛距離為20-50公尺，大面積共同懸掛效果更佳。2.摘除卵塊：若發現葉背有毛狀卵塊，則摘除葉片，此動作可瞬間清除300-500顆即將孵化的卵粒。3.蘇力菌防治幼蟲：輪流噴施不同廠牌的蘇力菌降低幼蟲密度，蘇力菌可有效殺死初齡的夜蛾幼蟲，亦為對環境安全的微生物製劑，對人體無害。另一方面，蘇力菌也能與殺蟲農藥混合施用，可省工並降低抗藥性的發生。4.合理使用農藥：防治夜蛾的藥劑很多，應參考植物保護手冊推薦藥劑，輪流施用兩種以上藥劑避免抗藥性產生，同時應遵守安全採收期及施用倍數等使用方法，避免造成農藥殘留。\n']
[1, 3]


In [2]:
import pandas as pd

In [3]:
chem = pd.read_excel('data\\Keywords\\02chem.list.xlsx', engine='openpyxl', header=None)
crop = pd.read_excel('data\\Keywords\\02crop.list.xlsx', engine='openpyxl', header=None)
pest = pd.read_excel('data\\Keywords\\02pest.list.xlsx', engine='openpyxl', header=None)

In [4]:
cropf = []
for i in range(len(crop)):
    temp = list(crop.loc[i])
    temp1 = []
    for j in temp:
        if type(j) == type(''):
            temp1.append(j)
    cropf.append(temp1.copy())
cropf

[['文旦柚', '文旦', '麻豆文旦'],
 ['水稻'],
 ['青蔥', '蔥'],
 ['龍鬚菜'],
 ['韭菜'],
 ['甘藍'],
 ['西瓜'],
 ['芋頭'],
 ['香蕉'],
 ['甘藷'],
 ['玉米'],
 ['胡瓜'],
 ['絲瓜'],
 ['洋香瓜'],
 ['菠菜'],
 ['萵苣'],
 ['十字花科'],
 ['豆科'],
 ['大蒜'],
 ['茼蒿'],
 ['落花生', '花生'],
 ['蔬菜'],
 ['田菁'],
 ['毛豆'],
 ['豌豆'],
 ['蓮花'],
 ['梨', '中國梨', '高接梨'],
 ['荔枝', '玉荷包荔枝'],
 ['龍眼'],
 ['蓮霧'],
 ['欒樹', '台灣欒樹'],
 ['果樹'],
 ['草莓', '草莓苗期'],
 ['柑橘'],
 ['紅棗'],
 ['柿子', '甜柿'],
 ['桃子', '桃'],
 ['李子'],
 ['枇杷'],
 ['楊桃'],
 ['檬果', '芒果'],
 ['木瓜'],
 ['番石榴', '芭樂'],
 ['檸檬'],
 ['印度棗'],
 ['番茄', '小果番茄', '橙蜜香番茄', '橙果小番茄'],
 ['馬鈴薯'],
 ['紅龍果'],
 ['棗'],
 ['蜜棗'],
 ['瓜果類'],
 ['豆菜類'],
 ['洋蔥'],
 ['豆類'],
 ['龍柏'],
 ['棗子'],
 ['高粱'],
 ['大豆'],
 ['香瓜'],
 ['南瓜'],
 ['橄欖'],
 ['葡萄'],
 ['洋桔梗'],
 ['柑桔'],
 ['百香果'],
 ['番荔枝'],
 ['鳳梨釋迦', '釋迦'],
 ['樹豆'],
 ['桶柑'],
 ['茂谷柑'],
 ['臍橙'],
 ['晚崙西亞', '晚崙西亞橙', '丁香'],
 ['荖花'],
 ['荖葉'],
 ['水蜜桃'],
 ['小米'],
 ['金針', '金針菜'],
 ['蘭花'],
 ['鳳梨'],
 ['酪梨'],
 ['杭菊'],
 ['花卉'],
 ['白柚'],
 ['椪柑'],
 ['柳橙', '柳丁'],
 ['西施柚'],
 ['蔬果類'],
 ['明尼吉柚'],
 ['葡萄柚'],
 ['葉菜類'],
 ['雜糧'],
 ['雜草'],


In [5]:
chemf = []
for i in range(len(chem)):
    temp = list(chem.loc[i])
    temp1 = []
    for j in temp:
        if type(j) == type(''):
            temp1.append(j)
    chemf.append(temp1.copy())
chemf

[['貝芬硫醌', '貝芬硫可濕性粉劑', '貝芬硫琨'],
 ['腈硫醌', '硫水懸劑', '硫水分散性粒劑', '硫可濕性粉劑', '腈硫醌水懸劑', '睛硫琨水懸劑', '腈硫醌可濕性粉劑'],
 ['鋅錳乃浦', '鋅錳乃浦水懸劑', '鋅錳乃浦可濕性粉劑', '鋅錳乃普水懸劑'],
 ['性費洛蒙', '費洛蒙', '性費洛', '費洛蒙緩釋劑'],
 ['蘇力菌', '蘇力菌水分散性粒劑', '蘇力菌可濕性粉劑', '生物製劑蘇力菌', '蘇力菌製劑'],
 ['比多農', '比多農可濕性粉劑'],
 ['夏油', '夏油(乙)', '四季夏油'],
 ['亞磷酸', '亞磷酸稀釋液'],
 ['乳化葵花油', '葵花油乳化液'],
 ['窄域油'],
 ['核多角體病毒'],
 ['苦楝油'],
 ['微生物製劑'],
 ['三賽唑', '三賽唑可濕性粉劑', '三賽唑水懸劑', '三賽唑可溼性粉劑', '三賽唑可濕性粉', '賽唑可濕性粉劑'],
 ['亞賜圃', '亞賜圃乳劑', '亞賜圃可濕性粉劑'],
 ['嘉賜黴素', '嘉賜黴素溶液', '嘉賜黴素可溼性粉劑', '嘉賜黴素可濕性粉劑', '嘉賜黴素可施性粉劑', '嘉賜黴素水溶性粒劑'],
 ['喜樂克拉', '喜樂克拉乳劑'],
 ['護粒松', '護粒松乳劑'],
 ['芬殺松', '芬殺松乳劑', '芬殺松乳劑稀釋'],
 ['加保利', '加保利可濕性粉劑', '加保利可溼性粉劑水懸劑', '加保利可濕性粉劑可濕性粉劑', '加保利可濕性粉劑稀釋'],
 ['加保扶', '加保扶水懸劑', '加保扶粒劑', '加保扶水懸劑稀釋'],
 ['第滅寧', '第滅寧水懸劑', '第滅寧乳劑'],
 ['甲基多保淨', '甲基多保淨水懸劑', '甲基多保淨可濕性粉劑', '甲基多保淨軟膏劑'],
 ['嘉賜三賽唑', '嘉賜三賽唑可濕性粉劑', '賜三賽唑可濕性粉劑', '嘉賜三塞唑可濕性粉劑', '加賜三賽唑可濕性粉劑'],
 ['護粒三賽唑', '護粒三賽唑可濕性粉劑', '護粒三塞唑可濕性粉劑'],
 ['撲殺培丹', '撲殺培丹粒劑'],
 ['撲殺熱', '撲殺熱藥劑', '撲殺熱粒劑'],
 ['保米熱斯', '保米熱必斯可濕性粉劑', '保米熱斯可濕性粉劑'],
 ['肉桂

In [6]:
pestf = []
for i in range(len(pest)):
    temp = list(pest.loc[i])
    temp1 = []
    for j in temp:
        if type(j) == type(''):
            temp1.append(j)
    pestf.append(temp1.copy())
pestf

[['斜紋夜蛾', '斜紋夜盜蟲', '黑蟲', '行軍蟲', '黑肚蟲', '夜盜蟲'],
 ['甜菜夜蛾', '蔥仔管蟲', '管仔蟲'],
 ['黑點病'],
 ['軟腐病'],
 ['疫病'],
 ['炭疽病'],
 ['潰瘍病'],
 ['白絹病'],
 ['黑腐病'],
 ['紫斑病'],
 ['黑斑病', '細菌性黑斑病', '鬼頭病', '輪斑病'],
 ['露菌病'],
 ['根螨'],
 ['薊馬'],
 ['瘤野螟', '稻縱捲葉蟲', '捲葉蟲', '葉尾蟲', '縱捲葉蟲'],
 ['褐飛蝨', '稻蝨', '跳仔'],
 ['白背飛蝨'],
 ['斑飛蝨', '穗苔'],
 ['梨木蝨'],
 ['黑星病'],
 ['煤紋病'],
 ['稻熱病', '稻瘟'],
 ['荔枝椿象', '臭青龜仔', '臭屁蟲', '臭椿象', '荔椿'],
 ['白葉枯病'],
 ['木蝨'],
 ['東方果實蠅', '蜂仔'],
 ['穗稻熱病', '吊穗', '吊狗'],
 ['葉稻熱病'],
 ['螟蟲'],
 ['水稻縞葉枯病'],
 ['露疫病'],
 ['鬼帚病'],
 ['紋枯病', '臭腳銅'],
 ['二化螟', '鑽心蟲'],
 ['三化螟'],
 ['草狀矮化病'],
 ['皺縮矮化病'],
 ['水稻水象鼻蟲'],
 ['小黃薊馬', '茶黃薊馬'],
 ['花薊馬'],
 ['煤煙病', '煤污病', '黑腳煙仔'],
 ['瓜實蠅', '瓜仔蜂'],
 ['灰象鼻蟲'],
 ['線蟲'],
 ['飛蝨類'],
 ['酸腐病'],
 ['壯鋏普癭蚋'],
 ['晚疫病', '黑骨病', '黑腳病', '爛葉仔病', '黑骨'],
 ['咖啡木蠹蛾'],
 ['台灣黃毒蛾'],
 ['小白紋毒蛾'],
 ['畸形病', '瘋花', '瘋欉', '公花'],
 ['瘡痂病'],
 ['白粉病'],
 ['褐斑病'],
 ['銀葉粉蝨', '白蒼蠅'],
 ['番茄嵌紋病毒'],
 ['胡瓜嵌紋病毒'],
 ['馬鈴薯病毒Y'],
 ['番茄黃化捲葉病毒', '番茄捲葉病'],
 ['霍香薊黃脈病毒'],
 ['輪斑病'],
 ['根腐病'],
 ['濕腐病'],
 ['黃萎病'],
 ['蚜蟲'],
 ['番茄斑點萎凋病毒'],
 [

In [7]:
import jieba

In [8]:
with open('data\\features.txt', 'w', encoding='UTF-8') as f:
    for feature in cropf+chemf+pestf:
        for word in feature:
            print(word, file = f)

In [9]:
jieba.load_userdict('data\\features.txt')

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\Howard\AppData\Local\Temp\jieba.cache
Loading model cost 0.561 seconds.
Prefix dict has been built successfully.


In [10]:
doc = []
doc_index = []
for i in range(1402):
    try:
        with open('data\\Train\\dataTrainComplete\\' + str(i) + '.txt', 'r', encoding='UTF-8') as f:
            doc.append(''.join(list(f)))
            doc_index.append(i)
    except:
        pass

In [11]:
tokens = []
for d in doc:
    temp = []
    res = jieba.cut(d)
    for word in res:
        temp.append(word)
    tokens.append(temp.copy())
tokens[9]

['發',
 '佈',
 '草莓苗期',
 '炭疽病',
 '防治',
 '警報',
 '，',
 '苗栗',
 '場籲',
 '請',
 '農友',
 '注意',
 '防治',
 '\n',
 '近來',
 '氣候',
 '高溫',
 '多',
 '濕',
 '，',
 '相當',
 '適合',
 '草莓苗期',
 '炭疽病',
 '發生',
 '，',
 '籲請',
 '農友',
 '注意',
 '防治',
 '適期',
 '。',
 '\n',
 '防治',
 '藥劑',
 '及',
 '方法',
 '：',
 '(',
 '1',
 ')',
 '53%',
 '腐絕快得寧可濕性粉劑',
 '1200',
 '倍',
 '。',
 '(',
 '2',
 ')',
 '24.9%',
 '待克利乳劑',
 '3000',
 '倍',
 '。',
 '(',
 '3',
 ')',
 '24.9%',
 '待克利水懸劑',
 '3000',
 '倍',
 '。',
 '(',
 '4',
 ')',
 '23.6%',
 '百克敏乳劑',
 '3000',
 '倍',
 '。',
 '防治',
 '應',
 '注意',
 '事項',
 '：',
 '(',
 '1',
 ')',
 '請',
 '加強',
 '母株',
 '的',
 '防治',
 '，',
 '若',
 '育苗',
 '區',
 '母株',
 '已',
 '呈',
 '現萎',
 '凋狀',
 '，',
 '請',
 '清除',
 '勿',
 '留在',
 '園區',
 '。',
 '(',
 '2',
 ')',
 '去除',
 '老葉',
 '之',
 '傷口',
 '為',
 '炭疽',
 '病菌',
 '侵入',
 '冠部',
 '之',
 '重要',
 '關鍵',
 '，',
 '老葉',
 '去除',
 '後',
 '應',
 '施用',
 '藥劑',
 '，',
 '以防',
 '病菌',
 '感染',
 '。',
 '育苗',
 '區之葉片',
 '、',
 '走',
 '蔓',
 '若',
 '有',
 '炭疽病',
 '斑',
 '，',
 '請將',
 '較',
 '嚴重',
 '之',
 '葉片',
 '或',
 '走',
 '蔓',
 '去除',
 '，',
 '再'

In [13]:
clean_tokens = []
for d in tokens:
    temp = []
    for word in d:
        if word > u'\u4e00' and word < u'\u9fff':
            temp.append(word)
    clean_tokens.append(temp.copy())
clean_tokens[0:2]

[['梅雨季',
  '來臨',
  '文旦',
  '黑點病',
  '易',
  '發生',
  '請',
  '注意',
  '病徵',
  '以及',
  '早加強',
  '防治',
  '措施',
  '月',
  '已',
  '進入',
  '梅雨季',
  '節',
  '近日',
  '連續',
  '降雨',
  '為',
  '文旦',
  '黑點病',
  '開始',
  '感染',
  '的',
  '時機',
  '往年',
  '文旦',
  '在',
  '經過',
  '月',
  '的',
  '春雨',
  '及',
  '梅雨季',
  '後',
  '原來',
  '長',
  '得',
  '亮麗',
  '的',
  '果實',
  '外表',
  '會',
  '開始',
  '出現',
  '許多',
  '小黑',
  '點',
  '現在',
  '文旦',
  '已',
  '開始',
  '進入',
  '中果期',
  '花蓮區',
  '農業',
  '改良',
  '場呼籲',
  '應',
  '注意',
  '防治',
  '除',
  '冬季',
  '清園',
  '作業外',
  '在',
  '月',
  '時應',
  '每月',
  '施用',
  '一次',
  '貝芬',
  '硫',
  '可濕性',
  '粉劑',
  '倍',
  '或',
  '硫',
  '水懸劑',
  '倍',
  '或',
  '鋅錳乃浦可濕性粉劑',
  '倍',
  '或',
  '鋅錳乃浦水懸劑',
  '倍',
  '等',
  '政府',
  '核准',
  '登記',
  '使用',
  '之藥劑',
  '防治',
  '並依',
  '登記',
  '使用',
  '方法',
  '使用',
  '尤其',
  '雨前',
  '及雨後要',
  '特別',
  '加強',
  '防治',
  '若遇',
  '連續',
  '降雨',
  '時則',
  '可',
  '利用',
  '間',
  '歇',
  '時',
  '分區',
  '進行',
  '施藥',
  '以',
  '即',
  '時',
  '達',
  '到',
  '防治效果'],
 ['夏季',
  '

In [16]:
for docu in range(len(clean_tokens)):
    for word in range(len(clean_tokens[docu])):
        for feature in cropf+chemf+pestf:
            if clean_tokens[docu][word] in feature:
                clean_tokens[docu][word] = feature[0]

In [17]:
tokens_with_space = []
for d in clean_tokens:
    doc_with_space='' #這部分是讓中文文本看起來比較像英文，方便vectorizer分析
    for token in d:
        doc_with_space += token
        doc_with_space += ' '
    tokens_with_space.append(doc_with_space)
tokens_with_space[0]

'梅雨季 來臨 文旦柚 黑點病 易 發生 請 注意 病徵 以及 早加強 防治 措施 月 已 進入 梅雨季 節 近日 連續 降雨 為 文旦柚 黑點病 開始 感染 的 時機 往年 文旦柚 在 經過 月 的 春雨 及 梅雨季 後 原來 長 得 亮麗 的 果實 外表 會 開始 出現 許多 小黑 點 現在 文旦柚 已 開始 進入 中果期 花蓮區 農業 改良 場呼籲 應 注意 防治 除 冬季 清園 作業外 在 月 時應 每月 施用 一次 貝芬 硫 可濕性 粉劑 倍 或 硫 水懸劑 倍 或 鋅錳乃浦 倍 或 鋅錳乃浦 倍 等 政府 核准 登記 使用 之藥劑 防治 並依 登記 使用 方法 使用 尤其 雨前 及雨後要 特別 加強 防治 若遇 連續 降雨 時則 可 利用 間 歇 時 分區 進行 施藥 以 即 時 達 到 防治效果 '

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(tokens_with_space)
print(tfidf_matrix.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
from sklearn.metrics.pairwise import cosine_similarity
cosinescore = cosine_similarity(tfidf_matrix,tfidf_matrix)

In [21]:
cosinescore

array([[1.        , 0.04839242, 0.06646411, ..., 0.0344946 , 0.03272729,
        0.09046189],
       [0.04839242, 1.        , 0.1175213 , ..., 0.04020826, 0.0394831 ,
        0.06958709],
       [0.06646411, 0.1175213 , 1.        , ..., 0.04372889, 0.04863052,
        0.07554997],
       ...,
       [0.0344946 , 0.04020826, 0.04372889, ..., 1.        , 0.9663951 ,
        0.14955851],
       [0.03272729, 0.0394831 , 0.04863052, ..., 0.9663951 , 1.        ,
        0.15979573],
       [0.09046189, 0.06958709, 0.07554997, ..., 0.14955851, 0.15979573,
        1.        ]])

In [12]:
with open('data\\TrainLabel.csv') as ans:
    raw = list(ans)[1:]
    answersheet = []
    for pair in raw:
        answersheet.append(pair.split('\n')[0].split(','))
answersheet[0:20]

[['3', '415'],
 ['3', '649'],
 ['9', '5'],
 ['25', '32'],
 ['25', '41'],
 ['26', '37'],
 ['27', '46'],
 ['29', '72'],
 ['32', '25'],
 ['32', '41'],
 ['34', '40'],
 ['35', '66'],
 ['35', '75'],
 ['35', '191'],
 ['40', '34'],
 ['41', '25'],
 ['41', '32'],
 ['44', '34'],
 ['44', '40'],
 ['44', '806']]

In [14]:
one_directional = 0
two_directional = 0
total = len(answersheet)
for rel in answersheet:
    if [rel[1], rel[0]] in answersheet:
        two_directional += 1
    else:
        one_directional += 1
print(one_directional)
print(two_directional)
print(total)
print(one_directional/total)
print(two_directional/total)

999
382
1381
0.723388848660391
0.27661115133960895


In [23]:
def f1score(gen, ans):
    tp = 0
    fp = 0
    fn = 0
    for pair in gen:
        if (pair in ans)|([pair[1],pair[0]] in ans):
            tp += 1
        else:
            fp += 1
    for pair in ans:
        if not ((pair in gen)|([pair[1],pair[0]] in gen)):
            fn += 1
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    score = 2*(precision*recall/(precision+recall))
    return score

In [24]:
for i in range(len(doc_index)):
    doc_index[i] = str(doc_index[i])

In [25]:
criteria = 0.6
dx = 0.01
f1last = 0

for z in range(100):
    gen_pairs = []
    gen_pairsdx = []
    for i in range(len(cosinescore)):
        for j in range(i):
            if cosinescore[i][j] > criteria:
                gen_pairs.append([doc_index[i],doc_index[j]])
            if cosinescore[i][j] > (criteria+dx):
                gen_pairsdx.append([doc_index[i],doc_index[j]])
    f1 = f1score(gen_pairs, answersheet)
    f1dx = f1score(gen_pairsdx, answersheet)
    criteria += ((f1dx-f1)/dx)*0.2*((100-z)/100)
    print('iteration : ' + str(z+1))
    print('criteria : ' + str(criteria))
    print('f1 : ' + str(f1))


iteration : 1
criteria : 0.6558541330745943
f1 : 0.4191139870582379
iteration : 2
criteria : 0.40519968588012684
f1 : 0.40911557243624525
iteration : 3
criteria : 0.46146778341369854
f1 : 0.4084084084084084
iteration : 4
criteria : 0.5039067465897658
f1 : 0.4117419853225184
iteration : 5
criteria : 0.45625839582392713
f1 : 0.4207879295892708
iteration : 6
criteria : 0.46705569533380814
f1 : 0.41479222264582544
iteration : 7
criteria : 0.48783790980239833
f1 : 0.41522762951334385
iteration : 8
criteria : 0.5431689324704921
f1 : 0.4184715978749489
iteration : 9
criteria : 0.6437882572279634
f1 : 0.4135440180586907
iteration : 10
criteria : 0.5307621864349825
f1 : 0.417243214475785
iteration : 11
criteria : 0.5578743731935455
f1 : 0.41163508153371525
iteration : 12
criteria : 0.5502036125816064
f1 : 0.41923436041083106
iteration : 13
criteria : 0.5704954518898387
f1 : 0.4175824175824176
iteration : 14
criteria : 0.5623225025472935
f1 : 0.41754051477597715
iteration : 15
criteria : 0.50585

In [26]:
gen_pairs[0:30]

[['9', '5'],
 ['14', '12'],
 ['29', '12'],
 ['32', '25'],
 ['34', '27'],
 ['37', '26'],
 ['40', '27'],
 ['40', '34'],
 ['41', '25'],
 ['41', '32'],
 ['46', '27'],
 ['46', '34'],
 ['46', '40'],
 ['54', '27'],
 ['54', '34'],
 ['54', '40'],
 ['54', '46'],
 ['57', '12'],
 ['57', '29'],
 ['64', '12'],
 ['64', '29'],
 ['64', '57'],
 ['65', '27'],
 ['65', '34'],
 ['65', '40'],
 ['65', '46'],
 ['65', '54'],
 ['66', '35'],
 ['68', '67'],
 ['70', '29']]

In [27]:
doc = []
doc_index = []
for i in range(1402):
    test_gen = []
    try:
        with open('data\\dataPublicComplete\\dataPublicComplete\\' + str(i) + '.txt', 'r', encoding='UTF-8') as f:
            doc.append(''.join(list(f)))
            doc_index.append(i)
    except:
        pass
tokens = []
for d in doc:
    temp = []
    res = jieba.cut(d)
    for word in res:
        temp.append(word)
    tokens.append(temp.copy())
clean_tokens = []
for d in tokens:
    temp = []
    for word in d:
        if word > u'\u4e00' and word < u'\u9fff':
            temp.append(word)
    clean_tokens.append(temp.copy())
for docu in range(len(clean_tokens)):
    for word in range(len(clean_tokens[docu])):
        for feature in cropf+chemf+pestf:
            if clean_tokens[docu][word] in feature:
                clean_tokens[docu][word] = feature[0]
tokens_with_space = []
for d in clean_tokens:
    doc_with_space='' #這部分是讓中文文本看起來比較像英文，方便vectorizer分析
    for token in d:
        doc_with_space += token
        doc_with_space += ' '
    tokens_with_space.append(doc_with_space)
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(tokens_with_space)
cosinescore = cosine_similarity(tfidf_matrix,tfidf_matrix)
for i in range(len(cosinescore)):
    for j in range(i):
        if cosinescore[i][j] > criteria:
            test_gen.append([doc_index[i],doc_index[j]])

test_gen = [['Test','Reference']] + test_gen
            
import csv

with open('test_result1209-2.csv', 'w', encoding='UTF-8', newline='') as f:
    writer = csv.writer(f)
    for pair in test_gen:
        writer.writerow(pair)